name: xilinx-kernel
summary: The Ubuntu generic Linux kernel
description: This Ubuntu generic Linux kernel
grade: stable
confinement: strict
type: kernel
build-base: core18
adopt-info: kernel

parts:
  kernel:
    after:
      - firmware
    plugin: kernel
    source: .
    source-type: git
    source-depth: 1
    kconfigflavour: xilinx-zynqmp
    kernel-image-target: Image
    kconfigs:
      - CONFIG_DEBUG_INFO=n
    override-build: |
      cp debian/scripts/retpoline-extract-one \
        ${SNAPCRAFT_PART_BUILD}/scripts/ubuntu-retpoline-extract-one
      snapcraftctl build
      cp ${SNAPCRAFT_PART_INSTALL}/dtbs/xilinx/*.dtb ${SNAPCRAFT_PART_INSTALL}/dtbs/
      mkdir -p ${SNAPCRAFT_PART_INSTALL}/lib
      ln -sf ../modules ${SNAPCRAFT_PART_INSTALL}/lib/modules
      ln -sf ../firmware ${SNAPCRAFT_PART_INSTALL}/lib/firmware
      snapcraftctl set-version $(git describe --tags | cut -c 15-)
    kernel-with-firmware: false
    organize:
      initrd.img: initrd
      kernel.img: Image
    prime:
      - -initrd*
      - -Image*

  firmware:
    plugin: nil
    source: debian
    stage-packages:
      - linux-firmware
      - wireless-regdb
    organize:
      lib/firmware: firmware
    prime:
      - -usr
      - -lib

  initrd-overlay:
    plugin: nil
    source: initrd-overlay
    after:
      - kernel
      - firmware
    stage-packages:
      - wireless-regdb
    override-build: |
      echo "Preparing overlay initrd"
      mkdir -p lib/firmware
      cp -r ${SNAPCRAFT_STAGE}/firmware/regulatory.db* lib/firmware/
      find . | cpio --quiet -o -H newc | lzma -7 > ${SNAPCRAFT_PART_INSTALL}/initrd-overlay.img
      cat ${SNAPCRAFT_STAGE}/initrd ${SNAPCRAFT_PART_INSTALL}/initrd-overlay.img > ${SNAPCRAFT_PART_INSTALL}/initrd.img
    organize:
      lib/firmware/: firmware/
    prime:
      - initrd.img
      - firmware

  firmware:
    plugin: nil
    stage-packages:
      - linux-firmware
      - wireless-regdb
    organize:
      lib/firmware: firmware
    prime:
      - -usr
      - -lib

  fit-image:
    plugin: nil
    after:
      - kernel
      - initrd-overlay
    override-build: |
      cp ${SNAPCRAFT_STAGE}/Image .
      cp ${SNAPCRAFT_STAGE}/initrd.img .
      cp -r ${SNAPCRAFT_STAGE}/dtbs .
      cp ${SNAPCRAFT_PROJECT_DIR}/image.its .
      mkimage -D "-I dts -O dtb -p 2000" -f image.its -r ${SNAPCRAFT_PART_INSTALL}/kernel.img

build-packages:
    - dpkg-dev
    - libssl-dev
    - libfdt-dev
    - cpio
    - flex
    - bison
    - u-boot-tools
    - device-tree-compiler
