obj-y 	+= host/echo/
obj-y 	+= host/rsh/
obj-y   += host/veth/
obj-y   += host/relay/

obj-y   += clnt/rsh/
obj-y   += clnt/echo/
obj-y 	+= clnt/veth/
obj-y 	+= clnt/relayexample/

obj-y   += common/rsh/
obj-y   += common/veth/
