
obj-$(CONFIG_AMBALINK_RPC) 	+= aipc_nl.o
obj-$(CONFIG_AMBALINK_RPC) 	+= aipc_router.o
obj-$(CONFIG_AMBALINK_RPC) 	+= rpmsg_rpc.o
obj-$(CONFIG_AMBALINK_LNX1_RPC2) 	+= rpmsg_rpc2_host.o
obj-$(CONFIG_AMBALINK_LNX2_RPC2) 	+= rpmsg_rpc2_clnt.o

obj-$(CONFIG_AMBALINK_RFS) 	+= rpmsg_rfs.o

obj-$(CONFIG_AMBALINK_VFFS) 	+= rpmsg_vffs.o

