#!/bin/sh

set -eu

# Always pefer to use modeevn if it is available
if [ -e "/run/mnt/data/system-data/var/lib/snapd/modeenv" ]; then
  mode="$(sed -n 's/mode=\([^[:space:]]*\)/\1/p' /run/mnt/data/system-data/var/lib/snapd/modeenv)"
else
  mode="$(/usr/libexec/core/get-arg snapd_recovery_mode || true)"
fi

if [ "${mode}" != "install" ]; then
    exit 0
fi

if /usr/libexec/core/get-arg quiet; then
    exit 0
fi

mkdir -p /run/systemd/journald.conf.d
cat <<EOF >/run/systemd/journald.conf.d/core-override.conf
[Journal]
ForwardToConsole=true
EOF
