# SPDX-License-Identifier: GPL-2.0
# Copyright (C) 2021 Canonical Ltd
name: imx-kernel
summary: i.mx linux kernel
description: The i.MX Ubuntu kernel package as a snap

grade: stable
build-base: core20
confinement: strict
type: kernel
adopt-info: kernel

architectures:
  - build-on: amd64
    run-on: armhf, arm64
  - build-on: armhf
    run-on: armhf
  - build-on: arm64
    run-on: arm64

parts:
    kernel:
        plugin: x-kernel
        kdefconfig: [ "snappy_defconfig" ]
        kernel-with-firmware: false
        kernel-image-target:
            arm64: Image
            armhf: zImage
        kernel-initrd-channel: beta
        kernel-initrd-compression: gz
        override-build: |
            snapcraftctl build
            snapcraftctl set-version $(git --git-dir=${SNAPCRAFT_PROJECT_DIR}/.git describe --tags | cut -c 12-42)
        organize:
            kernel.img: Image
  firmware:
    plugin: nil
    stage-packages:
      - linux-firmware
    organize:
      lib/firmware: firmware
    prime:
      - -usr
      - -lib

build-packages:
    - bison
    - device-tree-compiler
    - dpkg-dev
    - flex
    - initramfs-tools-core
    - libfdt-dev
    - libssl-dev
    - python3-crypto
    - python3-pycryptodome
    - python3-pyelftools
    - python3-serial
    - u-boot-tools
    - wget
    - libjson-c-dev:${SNAPCRAFT_TARGET_ARCH}
    - libcryptsetup-dev:${SNAPCRAFT_TARGET_ARCH}
    - to armhf:
        - binutils-arm-linux-gnueabi
        - gcc-arm-linux-gnueabi
    - to arm64:
        - gcc-aarch64-linux-gnu
