# SPDX-License-Identifier: GPL-2.0
# Copyright (C) 2021 Canonical Ltd
name: imx-kernel
summary: i.mx linux kernel
description: The i.MX Ubuntu kernel package as a snap

grade: stable
build-base: core22
confinement: strict
type: kernel
adopt-info: kernel

architectures:
  - build-on: [amd64, arm64]
    build-for: arm64
  - build-on: [amd64, arm64, armhf]
    build-for: armhf

parts:
  kernel:
    plugin: kernel
    kernel-kdefconfig: [ "snappy_defconfig" ]
    kernel-with-firmware: false
    kernel-image-target:
      arm64: Image
      armhf: zImage
    kernel-initrd-compression: zstd
    kernel-initrd-stage-firmware: true
    override-build: |
      craftctl default
      craftctl set version=$(git --git-dir=${CRAFT_PROJECT_DIR}/.git describe --tags | cut -c 12-42)
    organize:
      kernel.img: Image
    override-prime: |
      craftctl default
      # Trim firmware
      ${CRAFT_STAGE}/trim-firmware ${CRAFT_PRIME}
      # make sure we have all ath10 firmware files
      cp ${CRAFT_STAGE}/firmware/ath10k/QCA9377/hw1.0/* ${CRAFT_PRIME}/firmware/ath10k/QCA9377/hw1.0

  firmware:
    plugin: dump
    source: https://git.launchpad.net/~canonical-kernel-snaps/+git/kernel-snaps-uc22
    source-type: git
    source-branch: main
    stage-packages:
      - linux-firmware
      - wireless-regdb
    organize:
      lib/firmware: firmware
    stage:
      - -firmware/brcm/brcmfmac43455-sdio.bin
      - -firmware/brcm/brcmfmac43455-sdio.clm_blob
      - -firmware/brcm/brcmfmac4356-pcie.bin
      - -firmware/brcm/brcmfmac4356-pcie.clm_blob
    prime:
      - firmware

build-packages:
  - bison
  - device-tree-compiler
  - dpkg-dev
  - flex
  - libfdt-dev
  - libssl-dev
  - python3-cryptography
  - python3-pycryptodome
  - python3-pyelftools
  - python3-serial
  - u-boot-tools
  - wget
  - libjson-c-dev:${CRAFT_TARGET_ARCH}
  - libcryptsetup-dev:${CRAFT_TARGET_ARCH}
  - to armhf:
    - binutils-arm-linux-gnueabi
    - gcc-arm-linux-gnueabi
  - to arm64:
    - on amd64:
      - gcc-aarch64-linux-gnu
    - on arm64:
      - gcc
