name: imx-kernel
version: null
version-script: |
    . debian/debian.env
    dpkg-parsechangelog -l $DEBIAN/changelog -S version
summary: The Ubuntu iMX Linux kernel
description: This Ubuntu Linux kernel for NXP iMX family of devices
grade: stable
confinement: strict
type: kernel

architectures:
  - build-on: amd64
    run-on: armhf, arm64
  - build-on: armhf
    run-on: armhf
  - build-on: arm64
    run-on: arm64

parts:
    kernel:
        after:
            - firmware
        plugin: kernel
        source: .
        kdefconfig: [ "snappy_defconfig" ]
        kernel-with-firmware: false
        kernel-image-target: zImage
        override-build: |
            snapcraftctl build
            mkdir -p ${SNAPCRAFT_PART_INSTALL}/lib
            ln -sf ../modules ${SNAPCRAFT_PART_INSTALL}/lib/modules
        stage:
            - System.map-*
            - config-*
            - dtbs
            - initrd.img
            - kernel.img
            - lib
            - modules

    firmware:
        plugin: nil
        stage-packages:
            - linux-firmware
        override-build: |
            snapcraftctl build
            mkdir -p ${SNAPCRAFT_PART_INSTALL}/firmware/wlan \
                     ${SNAPCRAFT_PART_INSTALL}/firmware/smsc75xx \
                     ${SNAPCRAFT_PART_INSTALL}/lib
            ln -fs ../firmware ${SNAPCRAFT_PART_INSTALL}/lib/firmware
        stage:
            - -firmware/amd
            - -firmware/amdgpu
            - -firmware/cavium
            - -firmware/dpaa2
            - -firmware/i915
            - -firmware/intel
            - -firmware/iwlwifi-*
            - -firmware/liquidio
            - -firmware/matrox
            - -firmware/mediatek
            - -firmware/mellanox
            - -firmware/mrvl
            - -firmware/netronome
            - -firmware/nvidia
            - -firmware/qed
            - -firmware/radeon
            - -firmware/rockchip
            - -firmware/qcom
            - -firmware/qca
        organize:
            lib/firmware: firmware
        prime:
            - -usr
            - -lib

build-packages:
    - dpkg-dev
    - u-boot-tools
    - libssl-dev
    - libfdt-dev
    - flex
    - bison
    - initramfs-tools-core
