name: snapdragon-kernel
summary: Snapdragon kernel
description: This is a snapdragon snapped kernel, based off linaro kernel
grade: stable
confinement: strict
type: kernel
adopt-info: kernel

architectures:
  - build-on: [amd64, arm64]
    run-on: arm64

parts:
  kernel:
    after:
      - firmware
    plugin: x-kernel
    source: .
    source-type: git
    kconfigflavour: snapdragon
    kernel-with-firmware: false
    kernel-image-target: Image.gz
    kconfigs:
      - CONFIG_DEBUG_INFO=n
    override-build: |
      snapcraftctl build
      kernel_version="$(git --git-dir=${SNAPCRAFT_PART_SRC}/.git describe --tags  | cut -c 14-)"
      snapcraftctl set-version ${kernel_version}
    stage:
      - dtbs
      - System.map-*
      - config-*
      - initrd.img
      - kernel.img
      - modules
    prime:
      - -dtbs
      - -initrd.img
      - -kernel.img

  firmware:
    plugin: nil
    stage-packages:
      - linux-firmware
      - wireless-regdb
    stage:
      - -firmware/amd
      - -firmware/amdgpu
      - -firmware/asihpi
      - -firmware/cavium
      - -firmware/cxgb3
      - -firmware/cxgb4
      - -firmware/dpaa2
      - -firmware/i915
      - -firmware/intel
      - -firmware/iwlwifi-*
      - -firmware/liquidio
      - -firmware/matrox
      - -firmware/mediatek
      - -firmware/mellanox
      - -firmware/mrvl
      - -firmware/moxa
      - -firmware/netronome
      - -firmware/nvidia
      - -firmware/qed
      - -firmware/radeon
      - -firmware/rockchip
      - -firmware/ath10k/QCA9377/hw1.0/firmware-5.bin
      - -firmware/ath3k-1.fw
      - -firmware/qca/htbtfw20.tlv
      - -firmware/qcom
      - -firmware/s5p*
      - -usr
      - -lib
    organize:
      lib/firmware: firmware
    prime:
      - -usr
      - -lib

build-packages:
    - dpkg-dev
    - android-tools-mkbootimg
    - libssl-dev
    - libfdt-dev
    - cpio
    - flex
    - bison
    - wget
    - gcc-aarch64-linux-gnu
    - libjson-c-dev:arm64
