# SPDX-License-Identifier: GPL-2.0
# Copyright (C) 2021 Canonical Ltd
name: imx-kernel
summary: i.mx linux kernel
description: The i.MX Ubuntu kernel package as a snap

grade: stable
build-base: core22
confinement: strict
type: kernel
adopt-info: kernel

architectures:
  - build-on: [amd64, arm64]
    build-for: arm64
  - build-on: [amd64, arm64, armhf]
    build-for: armhf

parts:
  kernel:
    after:
      - firmware
    plugin: kernel
    kernel-kdefconfig: [ "snappy_defconfig" ]
    kernel-with-firmware: false
    kernel-image-target:
      arm64: Image
      armhf: zImage
    kernel-initrd-compression: zstd
    kernel-initrd-stage-firmware: true
    kernel-initrd-firmware:
      - firmware/imx/sdma/sdma-imx7d.bin
      - firmware/regulatory.db
      - firmware/regulatory.db.p7s
    build-environment:
      - PATH: "/usr/lib/ccache:${PATH}"
    override-build: |
      craftctl default
      craftctl set version=$(git --git-dir=${CRAFT_PROJECT_DIR}/.git describe --tags | cut -c 12-42)
    organize:
      kernel.img: Image
    override-prime: |
      craftctl default
      # Trim firmware
      trim_tool="https://git.launchpad.net/~canonical-kernel-snaps/+git/kernel-snaps-uc22/plain/trim-firmware"
      curl -s ${trim_tool} | bash /dev/stdin ${CRAFT_PRIME}
      # make sure we have all ath10 firmware files
      cp ${CRAFT_STAGE}/firmware/ath10k/QCA9377/hw1.0/* ${CRAFT_PRIME}/firmware/ath10k/QCA9377/hw1.0

  firmware:
    plugin: dump
    source: https://git.launchpad.net/~canonical-kernel-snaps/+git/kernel-snaps-uc22
    source-type: git
    source-branch: main
    stage-packages:
      - linux-firmware
      - wireless-regdb
    organize:
      lib/firmware: firmware
    stage:
      - -firmware/brcm/brcmfmac43455-sdio.bin
      - -firmware/brcm/brcmfmac43455-sdio.clm_blob
      - -firmware/brcm/brcmfmac4356-pcie.bin
      - -firmware/brcm/brcmfmac4356-pcie.clm_blob
    prime:
      - firmware

  firmware-nxp:
    after:
      - kernel
    plugin: dump
    source: https://github.com/NXP/imx-firmware.git
    source-type: git
    source-tag: lf-5.15.71_2.2.0
    organize:
      'cyw-wifi-bt/1CX_CYW4356/*': firmware/brcm/
      'cyw-wifi-bt/1FD_CYW4359/*': firmware/brcm/
      'cyw-wifi-bt/1MW_CYW43455/*': firmware/brcm/
      'brcm/': firmware/brcm/
      'nxp/FwImage_8997/*': firmware/nxp/
      'nxp/FwImage_8987/*': firmware/nxp/
      'nxp/wifi_mod_para.conf': firmware/nxp/
    stage:
      - firmware/brcm
      - firmware/nxp

  optee-os:
    after:
      - optee-uc-fde
      - optee-keys
    plugin: nil
    source: https://github.com/nxp-imx/imx-optee-os.git
    source-type: git
    source-tag: lf-5.15.71_2.2.0
    source-depth: 1
    build-environment:
      # depending on architecture
      # on arm64: we are building optee-os only to get build export dependency to build REE app
      # on armhf: we are building optee-os to be included in FIT image
      - to armhf:
        - CROSS_COMPILE_ta_arm32: "${CRAFT_ARCH_TRIPLET}-"
        - PLATFORM: "vexpress-qemu_virt"
        - CFG_USER_TA_TARGETS: "ta_arm32"
        - CFG_NS_ENTRY_ADDR: "0x82100000"
        - CFG_PAGEABLE_ADDR: "0x86800000"
        - CFG_DT_ADDR: "0x83000000"
        # 1GB DDR
        # export CFG_DDR_SIZE=0x40000000
        # 512MB DDR
        - CFG_DDR_SIZE: "0x20000000"
        - CFG_TEE_RAM_VA_SIZE: "0x00400000"
        - PLATFORM: "imx"
        - PLATFORM_FLAVOR: "mx6sxsabreauto"
        - CFG_WERROR: "y"
      - to arm64:
        - CROSS_COMPILE_ta_arm64: "${CRAFT_ARCH_TRIPLET}-"
        - CFG_ARM64_core: "y"
        - PLATFORM: "vexpress-qemu_armv8a"
        - CFG_USER_TA_TARGETS: "ta_arm64"
      - ARCH: "arm"
      - CROSS_COMPILE: "${CRAFT_ARCH_TRIPLET}-"
      - CROSS_COMPILE_core: "${CRAFT_ARCH_TRIPLET}-"
      - DEBUG: "0"
      - CFG_TEE_CORE_DEBUG: "n"
      - CFG_TEE_BENCHMARK: "n"
      - TA_PUBLIC_KEY: "${CRAFT_STAGE}/ta-keys/ta_public.pem"
    override-build: |
      # add optee-uc-fde TA
      cp -r ${CRAFT_STAGE}/optee-uc-fde/ta/fde_key_handler ${CRAFT_PART_BUILD}/ta/
      export OPTEE_VERSION=$(head -1 CHANGELOG.md  | sed 's/# OP-TEE - version \(.*\) (.*/\1/g')-imx
      make O=${CRAFT_PART_BUILD}/out -j$(nproc)
      if [ "${CRAFT_TARGET_ARCH}" = "armhf" ]; then
        # now build optee-os once more with added early TAs
        make O=${CRAFT_PART_BUILD}/out -j$(nproc) \
          CFG_EARLY_TA=y \
          EARLY_TA_PATHS="out/ta/pkcs11/fd02c9da-306c-48c7-a49c-bbd827ae86ee.stripped.elf \
                  out/ta/fde_key_handler/fd1b2a86-3668-11eb-adc1-0242ac120002.stripped.elf"

        cp ${CRAFT_PART_BUILD}/out/core/tee-raw.bin \
          ${CRAFT_PART_INSTALL}/tee.mx6sx.bin
      fi
      cp -r ${CRAFT_PART_BUILD}/out/export-ta_arm* ${CRAFT_PART_INSTALL}/export-ta_arm
    prime:
      - -*

  optee-client:
    plugin: nil
    source: https://github.com/OP-TEE/optee_client.git
    source-type: git
    source-tag: 3.19.0
    build-environment:
      - to armhf:
        - ARCH: "arm"
      - else:
        - ARCH: "${CRAFT_TARGET_ARCH}"
      - CROSS_COMPILE: "${CRAFT_ARCH_TRIPLET}-"
      - DEBUG: "0"
      - CFG_TEE_CLIENT_LOAD_PATH: ""
      - CFG_TA_TEST_PATH: "0"
      - SBINDIR: "/usr/sbin"
      - LIBDIR: "/usr/lib/${CRAFT_ARCH_TRIPLET}"
      - DESTDIR: "${CRAFT_PART_INSTALL}"
    override-build: |
      make O=${CRAFT_PART_BUILD}/out -j$(nproc)
      make install O=${CRAFT_PART_BUILD}/out
    prime:
      - usr/lib/*/lib*so*

build-packages:
  - bison
  - device-tree-compiler
  - dpkg-dev
  - flex
  - libfdt-dev
  - libssl-dev
  - python3-cryptography
  - python3-pycryptodome
  - python3-pyelftools
  - python3-serial
  - u-boot-tools
  - wget
  - libjson-c-dev:${CRAFT_TARGET_ARCH}
  - libcryptsetup-dev:${CRAFT_TARGET_ARCH}
  - to armhf:
    - binutils-arm-linux-gnueabi
    - gcc-arm-linux-gnueabi
  - to arm64:
    - on amd64:
      - gcc-aarch64-linux-gnu
    - on arm64:
      - gcc
