name: imx-kernel
version: null
version-script: |
    . debian/debian.env
    dpkg-parsechangelog -l $DEBIAN/changelog -S version
summary: The Ubuntu iMX Linux kernel
description: This Ubuntu Linux kernel for NXP iMX family of devices

grade: stable
confinement: strict
type: kernel
build-base: core20

parts:
    kernel:
        after:
            - firmware
        plugin: x-kernel
        source: .
        kdefconfig: [ "snappy_defconfig" ]
        kernel-with-firmware: false
        kernel-image-target:
            arm64: Image
        kernel-initrd-flavour: edge
        kernel-initrd-compression: gz
        stage:
            - System.map-*
            - config-*
            - dtbs
            - initrd.img
            - kernel.img
            - lib
            - modules

    firmware:
        plugin: nil
        stage-packages:
            - linux-firmware
        stage:
            - -firmware/amd
            - -firmware/amdgpu
            - -firmware/cavium
            - -firmware/dpaa2
            - -firmware/i915
            - -firmware/intel
            - -firmware/iwlwifi-*
            - -firmware/liquidio
            - -firmware/matrox
            - -firmware/mediatek
            - -firmware/mellanox
            - -firmware/mrvl
            - -firmware/netronome
            - -firmware/nvidia
            - -firmware/qed
            - -firmware/radeon
            - -firmware/rockchip
            - -firmware/qcom
            - -firmware/qca
        organize:
            lib/firmware: firmware
        prime:
            - firmware

build-packages:
    - dpkg-dev
    - u-boot-tools
    - libssl-dev
    - libfdt-dev
    - flex
    - bison
    - initramfs-tools-core
