# SPDX-License-Identifier: GPL-2.0
# Copyright (C) 2021 Canonical Ltd
name: imx-kernel
summary: i.mx linux kernel
description: The i.MX Ubuntu kernel package as a snap

grade: stable
build-base: core20
confinement: strict
type: kernel
adopt-info: kernel

architectures:
  - build-on: amd64
    run-on: armhf, arm64
  - build-on: armhf
    run-on: armhf
  - build-on: arm64
    run-on: arm64

parts:
    kernel:
        after:
            - firmware
        plugin: x-kernel
        kdefconfig: [ "snappy_defconfig" ]
        kernel-with-firmware: false
        kernel-image-target:
            arm64: Image
            armhf: zImage
        kernel-initrd-channel: beta
        kernel-initrd-compression: gz
        kernel-initrd-firmware:
            - firmware/imx/sdma/sdma-imx7d.bin
            - firmware/regulatory.db
            - firmware/regulatory.db.p7s
        override-build: |
            snapcraftctl build
            snapcraftctl set-version $(git --git-dir=${SNAPCRAFT_PROJECT_DIR}/.git describe --tags | cut -c 12-42)
        organize:
            kernel.img: Image
        override-prime: |
            snapcraftctl prime
            # Trim firmware
            ${SNAPCRAFT_STAGE}/trim-firmware ${SNAPCRAFT_PRIME}

    firmware:
        plugin: dump
        source: https://git.launchpad.net/~canonical-kernel-snaps/+git/kernel-snaps-uc22
        source-type: git
        source-branch: main
        stage-packages:
            - linux-firmware
            - wireless-regdb
        organize:
            lib/firmware: firmware
        stage:
            - -firmware/brcm/brcmfmac43455-sdio.bin
            - -firmware/brcm/brcmfmac4356-pcie.bin
        prime:
            - firmware

    firmware-nxp:
        after:
            - kernel
        plugin: dump
        source: https://github.com/NXP/imx-firmware.git
        source-type: git
        source-tag: lf-5.15.32_2.0.0
        organize:
            'cyw-wifi-bt/1CX_CYW4356/*': firmware/brcm/
            'cyw-wifi-bt/1FD_CYW4359/*': firmware/brcm/
            'cyw-wifi-bt/1MW_CYW43455/*': firmware/brcm/
            'brcm/': firmware/brcm/
            'nxp/FwImage_8997/*': firmware/nxp/
            'nxp/FwImage_8987/*': firmware/nxp/
            'nxp/wifi_mod_para.conf': firmware/nxp/
        stage:
            - firmware/brcm
            - firmware/nxp

build-packages:
    - bison
    - device-tree-compiler
    - dpkg-dev
    - flex
    - initramfs-tools-core
    - libfdt-dev
    - libssl-dev
    - python3-crypto
    - python3-pycryptodome
    - python3-pyelftools
    - python3-serial
    - u-boot-tools
    - wget
    - libjson-c-dev:${SNAPCRAFT_TARGET_ARCH}
    - libcryptsetup-dev:${SNAPCRAFT_TARGET_ARCH}
    - to armhf:
        - binutils-arm-linux-gnueabi
        - gcc-arm-linux-gnueabi
    - to arm64:
        - gcc-aarch64-linux-gnu
