name: snapdragon-kernel
summary: Snapdragon kernel
description: This is a snapdragon snapped kernel, based off linaro kernel
grade: stable
confinement: strict
type: kernel
adopt-info: kernel

architectures:
  - build-on: [amd64, arm64]
    run-on: arm64

build-base: core20

parts:
  kernel:
    after:
      - firmware
    plugin: x-kernel
    source: .
    source-type: git
    kdefconfig: [ "snappy_defconfig" ]
    kernel-with-firmware: false
    kernel-image-target: Image.gz
    kconfigs:
      - CONFIG_DEBUG_INFO=n
    override-build: |
      snapcraftctl build
      kernel_version="$(git --git-dir=${SNAPCRAFT_PART_SRC}/.git describe --tags  | cut -c 8-)"
      snapcraftctl set-version ${kernel_version}
    stage:
      - dtbs
      - System.map-*
      - config-*
      - initrd.img
      - kernel.img
      - modules
    prime:
      - -dtbs
      - -initrd.img
      - -kernel.img

  bootimg-db845c:
    plugin: nil
    after:
      - kernel
    override-build: |
      cat ${SNAPCRAFT_STAGE}/kernel.img ${SNAPCRAFT_STAGE}/dtbs/qcom/sdm845-db845c.dtb > Image.gz+db845c
      mkbootimg \
        --kernel Image.gz+db845c \
        --ramdisk ${SNAPCRAFT_STAGE}/initrd.img \
        --output ${SNAPCRAFT_PART_INSTALL}/boot.img \
        --pagesize 4096 \
        --base 0x80000000 \
        --kernel_offset 0x8000 \
        --ramdisk_offset 0x1000000 \
        --tags_offset 0x100 \
        --cmdline 'console=tty0 console=ttyMSM0,115200n8 clk_ignore_unused pd_ignore_unused snapd_lk_boot_disk=sde'
    prime:
      - boot.img

  bootimg-db820c:
    plugin: nil
    after:
      - kernel
    override-build: |
      cat ${SNAPCRAFT_STAGE}/kernel.img ${SNAPCRAFT_STAGE}/dtbs/qcom/apq8096-db820c.dtb > Image.gz+db820c
      mkbootimg \
        --kernel Image.gz+db820c \
        --ramdisk ${SNAPCRAFT_STAGE}/initrd.img \
        --output ${SNAPCRAFT_PART_INSTALL}/boot-db820c.img \
        --pagesize 4096 \
        --base 0x80000000 \
        --kernel_offset 0x8000 \
        --ramdisk_offset 0x1000000 \
        --tags_offset 0x100 \
        --cmdline 'console=tty0 console=ttyMSM0,115200n8 clk_ignore_unused pd_ignore_unused snapd_lk_boot_disk=sde'
      ln ${SNAPCRAFT_PART_INSTALL}/boot-db820c.img ${SNAPCRAFT_PART_INSTALL}/boot-ifc6640.img
    prime:
      - boot-db820c.img
      - boot-ifc6640.img

  bootimg-db410c:
    plugin: nil
    after:
      - kernel
    override-build: |
      cat ${SNAPCRAFT_STAGE}/kernel.img ${SNAPCRAFT_STAGE}/dtbs/qcom/apq8016-sbc.dtb > Image.gz+db410c
      mkbootimg \
        --kernel Image.gz+db410c \
        --ramdisk ${SNAPCRAFT_STAGE}/initrd.img \
        --output ${SNAPCRAFT_PART_INSTALL}/boot-db410c.img \
        --pagesize 2048 \
        --base 0x80000000 \
        --kernel_offset 0x8000 \
        --ramdisk_offset 0x1000000 \
        --tags_offset 0x100 \
        --cmdline 'console=tty0 console=ttyMSM0,115200n8 clk_ignore_unused pd_ignore_unused snapd_lk_boot_disk=mmcblk0'
    prime:
      - boot-db410c.img

  firmware:
    plugin: nil
    stage-packages:
      - linux-firmware
      - wireless-regdb
    stage:
      - -firmware/amd
      - -firmware/amdgpu
      - -firmware/asihpi
      - -firmware/cavium
      - -firmware/cxgb3
      - -firmware/cxgb4
      - -firmware/dpaa2
      - -firmware/i915
      - -firmware/intel
      - -firmware/iwlwifi-*
      - -firmware/liquidio
      - -firmware/matrox
      - -firmware/mediatek
      - -firmware/mellanox
      - -firmware/mrvl
      - -firmware/moxa
      - -firmware/netronome
      - -firmware/nvidia
      - -firmware/qed
      - -firmware/radeon
      - -firmware/rockchip
      - -firmware/ath10k/QCA9377/hw1.0/firmware-5.bin
      - -firmware/ath3k-1.fw
      - -firmware/qca/htbtfw20.tlv
      - -firmware/qcom
      - -firmware/s5p*
      - -usr
      - -lib
    organize:
      lib/firmware: firmware
    prime:
      - -usr
      - -lib

build-packages:
    - dpkg-dev
    - android-tools-mkbootimg
    - libssl-dev
    - libfdt-dev
    - cpio
    - flex
    - bison
    - wget
    - gcc-aarch64-linux-gnu
    - libjson-c-dev:arm64
