name: imx-kernel
version: null
version-script: |
    . debian/debian.env
    dpkg-parsechangelog -l $DEBIAN/changelog -S version
summary: i.mx linux kernel
description: The i.MX Ubuntu kernel package as a snap

grade: stable
build-base: core20
confinement: strict
type: kernel

architectures:
  - build-on: amd64
    run-on: armhf, arm64
  - build-on: armhf
    run-on: armhf
  - build-on: arm64
    run-on: arm64

parts:
    kernel:
        plugin: x-kernel
        source: .
        kdefconfig: [ "snappy_defconfig" ]
        kernel-with-firmware: false
        kernel-image-target:
            arm64: Image
            armhf: zImage
        kernel-initrd-channel: beta
        kernel-initrd-compression: gz
        override-build: |
            snapcraftctl build
            snapcraftctl set-version $(git --git-dir=${SNAPCRAFT_PART_SRC}/.git describe --tags | cut -c 12-42)
        organize:
            kernel.img: Image

    firmware:
        plugin: nil
        stage-packages:
            - linux-firmware
            - wireless-regdb
        stage:
            - -firmware/amd
            - -firmware/amdgpu
            - -firmware/asihpi
            - -firmware/cavium
            - -firmware/cxgb3
            - -firmware/cxgb4
            - -firmware/dpaa2
            - -firmware/i915
            - -firmware/intel
            - -firmware/iwlwifi-*
            - -firmware/liquidio
            - -firmware/matrox
            - -firmware/mediatek
            - -firmware/mellanox
            - -firmware/mrvl
            - -firmware/moxa
            - -firmware/netronome
            - -firmware/nvidia
            - -firmware/qed
            - -firmware/radeon
            - -firmware/rockchip
            - -firmware/ath10k/QCA9377/hw1.0/firmware-5.bin
            - -firmware/ath3k-1.fw
            - -firmware/qca/htbtfw20.tlv
            - -firmware/qcom
            - -firmware/s5p*
            - -firmware/brcm/brcmfmac43455-sdio.bin
            - -firmware/brcm/brcmfmac4356-pcie.bin
            - -usr
            - -lib
        organize:
            lib/firmware: firmware

build-packages:
    - bison
    - device-tree-compiler
    - dpkg-dev
    - flex
    - initramfs-tools-core
    - libfdt-dev
    - libssl-dev
    - python3-crypto
    - python3-pycryptodome
    - python3-pyelftools
    - python3-serial
    - u-boot-tools
    - wget
    - to armhf:
        - binutils-arm-linux-gnueabi
        - gcc-arm-linux-gnueabi
        - libjson-c-dev:armhf
    - to arm64:
        - gcc-aarch64-linux-gnu
        - libjson-c-dev:arm64
