name: ambarella-kernel
summary: Ambarella linux kernel for snappy
description: This is a Ambarella snapped kernel
grade: stable
confinement: strict
type: kernel
adopt-info: kernel

architectures:
  - build-on: [amd64, arm64]
    run-on: arm64

build-base: core18

parts:
    kernel:
        plugin: kernel
        source: .
        source-type: git
        kdefconfig: [ "defconfig", "ambarella_cv2_defconfig" ]
        kernel-with-firmware: false
        kernel-image-target: Image
        kconfigs:
            - CONFIG_DEBUG_INFO=n
        override-build: |
            cp debian/scripts/retpoline-extract-one \
                ${SNAPCRAFT_PART_BUILD}/scripts/ubuntu-retpoline-extract-one
            snapcraftctl build
            mkdir -p ${SNAPCRAFT_PART_INSTALL}/lib
            ln -sf ../modules ${SNAPCRAFT_PART_INSTALL}/lib/modules
            # snapcraftctl set-version $(git describe --tags | cut -c 19-)
            snapcraftctl set-version $(make kernelversion)
        stage:
            - System.map-*
            - config-*
            - initrd.img
            - kernel.img
            - lib
            - modules
            - -modules/*/build
            - -modules/*/source
        prime:
            - -initrd.img
            - -kernel.img

    lz4-tools:
        plugin: nil
        source: git+ssh://git.launchpad.net/~nuremberg-team/nuremberg/+git/amba-lz4tools
        source-type: git
        override-build: |
            gcc \
                host_lz4.c \
                liblz4.c \
                -DBUILD_HOST_TOOLS=yes \
                -o ${SNAPCRAFT_PART_INSTALL}/host_lz4
        prime:
             - -host_lz4

    bootimg:
        plugin: nil
        after:
            - lz4-tools
            - kernel
        override-build: |
            ${SNAPCRAFT_STAGE}/host_lz4 \
                ${SNAPCRAFT_STAGE}/kernel.img \
                kernel.lz4
            # number representation from 0 to 255 (one char long)
            chr() {
              printf "\\$(printf '%03o' "$1")"
            }
            # from 0 to 65535 (two char long)
            word() {
              chr $(($1 % 256))
              chr $(($1 / 256))
            }
            # from 0 to 4294967295 (four char long)
            dword() {
              word $(($1 % 65536))
              word $(($1 / 65536))
            }
            kernelSize=$(stat -L -c%s kernel.lz4)
            initrdSize=$(stat -L -c%s ${SNAPCRAFT_STAGE}/initrd.img)
            # first 4 bytes of the boot image represents size of the kernel image
            # so bootloader knows how much data to load
            dword ${kernelSize} > ${SNAPCRAFT_PART_INSTALL}/boot.img
            cat kernel.lz4 >> ${SNAPCRAFT_PART_INSTALL}/boot.img
            dword ${initrdSize} >> ${SNAPCRAFT_PART_INSTALL}/boot.img
            cat ${SNAPCRAFT_STAGE}/initrd.img >> ${SNAPCRAFT_PART_INSTALL}/boot.img

    amba-private-drivers:
        plugin: dump
        source: git+ssh://git.launchpad.net/~nuremberg-team/nuremberg/+git/amba-private-drivers
        source-type: git
        source-branch: sdk-3.0.0
        organize:
            "*": amba-private-drivers/
        prime:
            - -*

    amba-build:
        plugin: dump
        source: git+ssh://git.launchpad.net/~nuremberg-team/nuremberg/+git/amba-build
        source-type: git
        source-branch: uc-18-poc-rebase
        organize:
            "*": amba-build/
        prime:
            - -*

build-packages:
    - dpkg-dev
    - android-tools-mkbootimg
    - libssl-dev
    - libfdt-dev
    - cpio
    - flex
    - bison
    - wget
    - initramfs-tools-core
