name: qti-sa8155p-kernel
summary: Snapdragon kernel
description: This is a snapdragon snapped kernel, based off linaro kernel
grade: stable
confinement: strict
type: kernel
adopt-info: kernel

architectures:
  - build-on: [amd64, arm64]
    run-on: arm64

build-base: core20

parts:
  kernel:
    after:
      - firmware
    plugin: x-kernel
    source-type: git
    kdefconfig: [ "snappy_defconfig" ]
    kernel-with-firmware: false
    kernel-image-target: Image.gz
    kernel-enable-zfs-support: true
    kernel-initrd-compression: lz4
    kernel-initrd-modules:
      - atl1c
      - qcom-emac
      - phy-qcom-qusb2
      - slimbus
      - xhci-hcd
      - libarc4
    kconfigs:
      - CONFIG_DEBUG_INFO=n
    override-build: |
      snapcraftctl build
      kernel_version="$(git --git-dir=${SNAPCRAFT_PROJECT_DIR}/.git describe --tags  | cut -c 14-)"
      snapcraftctl set-version ${kernel_version}
    override-prime: |
      snapcraftctl prime
      ${SNAPCRAFT_STAGE}/trim-firmware ${SNAPCRAFT_PRIME}
    stage:
      - dtbs
      - System.map-*
      - config-*
      - initrd.img
      - kernel.img
      - modules
    prime:
      - -dtbs
      - -initrd.img
      - -kernel.img

  bootimg:
    plugin: nil
    after:
      - kernel
    override-build: |
      cat ${SNAPCRAFT_STAGE}/kernel.img \
          ${SNAPCRAFT_STAGE}/dtbs/qcom/apq8016-sbc.dtb \
          ${SNAPCRAFT_STAGE}/dtbs/qcom/apq8096-db820c.dtb \
          ${SNAPCRAFT_STAGE}/dtbs/qcom/sdm845-db845c.dtb \
          ${SNAPCRAFT_STAGE}/dtbs/qcom/sa8155p-adp.dtb \
          ${SNAPCRAFT_STAGE}/dtbs/qcom/sa8155p-iot-v2-adp.dtb \
          > Image.gz+dtbs
      mkbootimg \
        --kernel Image.gz+dtbs \
        --ramdisk ${SNAPCRAFT_STAGE}/initrd.img \
        --output ${SNAPCRAFT_PART_INSTALL}/boot.img.nonsecure \
        --pagesize 4096 \
        --base 0x80000000 \
        --kernel_offset 0x8000 \
        --ramdisk_offset 0x1000000 \
        --tags_offset 0x100 \
        --cmdline 'console=tty0 console=ttyMSM0,115200n8 clk_ignore_unused pd_ignore_unused'
    prime:
      - boot.img

  firmware:
    plugin: dump
    source: https://git.launchpad.net/~canonical-kernel-snaps/+git/kernel-snaps-uc22
    source-type: git
    source-branch: main
    stage-packages:
      - linux-firmware
      - wireless-regdb
    organize:
      lib/firmware: firmware
    prime:
      - firmware

build-packages:
    - dpkg-dev
    - android-tools-mkbootimg
    - libssl-dev
    - libfdt-dev
    - cpio
    - flex
    - bison
    - wget
    - gcc-aarch64-linux-gnu
