name: qti-sa8155p-kernel
summary: Snapdragon kernel
description: This is a snapdragon snapped kernel, based off linaro kernel
grade: stable
confinement: strict
type: kernel
adopt-info: kernel

architectures:
  - build-on: [amd64, arm64]
    build-for: arm64

build-base: core22

parts:
  kernel:
    after:
      - firmware
    plugin: kernel
    kernel-kdefconfig:
      - snappy_defconfig
    kernel-with-firmware: false
    kernel-image-target: Image.gz
    kernel-enable-zfs-support: true
    kernel-initrd-compression: zstd
    kernel-initrd-stage-firmware: true
    kernel-initrd-modules:
      - atl1c
      - qcom-emac
      - phy-qcom-qusb2
      - slimbus
      - xhci-hcd
      - libarc4
    kernel-kconfigs:
      - CONFIG_DEBUG_INFO=n
    override-build: |
      craftctl default
      kernel_version="$(git --git-dir=${CRAFT_PROJECT_DIR}/.git describe --tags  | cut -c 14-)"
      craftctl set version=${kernel_version}
    override-prime: |
      craftctl default
      ${CRAFT_STAGE}/trim-firmware ${CRAFT_PRIME}
    stage:
      - config-*
      - dtbs
      - initrd.img
      - kernel.img
      - lib
      - modules
      - System.map-*
    prime:
      - -dtbs
      - -initrd.img
      - -kernel.img

  bootimg:
    plugin: nil
    after:
      - kernel
    override-build: |
      cat ${CRAFT_STAGE}/kernel.img \
          ${CRAFT_STAGE}/dtbs/qcom/sa8155p-adp.dtb \
          ${CRAFT_STAGE}/dtbs/qcom/sa8155p-iot-v2-adp.dtb \
          > Image.gz+dtbs
      mkbootimg \
        --kernel Image.gz+dtbs \
        --ramdisk ${CRAFT_STAGE}/initrd.img \
        --output ${CRAFT_PART_INSTALL}/boot.img.nonsecure \
        --pagesize 4096 \
        --base 0x80000000 \
        --kernel_offset 0x8000 \
        --ramdisk_offset 0x1000000 \
        --tags_offset 0x100 \
        --cmdline 'console=tty0 console=ttyMSM0,115200n8 clk_ignore_unused pd_ignore_unused'
    prime:
      - boot.img

  firmware:
    plugin: dump
    source: https://git.launchpad.net/~canonical-kernel-snaps/+git/kernel-snaps-uc22
    source-type: git
    source-branch: main
    stage-packages:
      - linux-firmware
      - wireless-regdb
    organize:
      lib/firmware: firmware
    prime:
      - firmware

build-packages:
    - android-tools-mkbootimg
    - bison
    - cpio
    - dpkg-dev
    - flex
    - gcc-aarch64-linux-gnu
    - libfdt-dev
    - libssl-dev
