name: qti-sa8155p-kernel
version: null
version-script: |
    . debian/debian.env
    dpkg-parsechangelog -l $DEBIAN/changelog -S version
summary: Snapdragon kernel
description: This is a snapdragon snapped kernel, based off linaro kernel
grade: stable
confinement: strict
type: kernel

architectures:
  - build-on: [amd64, arm64]
    build-for: arm64

build-base: core22

parts:
  kernel:
    after:
      - firmware
    plugin: kernel
    kernel-kdefconfig:
      - snappy_defconfig
    kernel-with-firmware: false
    kernel-image-target: Image.gz
    kernel-initrd-compression: zstd
    kernel-initrd-stage-firmware: true
    kernel-initrd-modules:
      - atl1c
      - qcom-emac
      - phy-qcom-qusb2
      - slimbus
      - xhci-hcd
      - libarc4
    kernel-kconfigs:
      - CONFIG_DEBUG_INFO=n
    override-build: |
      craftctl default
      kernel_version="$(git --git-dir=${CRAFT_PROJECT_DIR}/.git describe --tags  | cut -c 14-)"
      craftctl set version=${kernel_version}
    stage:
      - config-*
      - dtbs
      - initrd.img
      - kernel.img
      - lib
      - modules
      - System.map-*
    prime:
      - -dtbs
      - -initrd.img
      - -kernel.img

  firmware:
    plugin: dump
    source: https://git.launchpad.net/~canonical-kernel-snaps/+git/kernel-snaps-uc22
    source-type: git
    source-branch: main
    stage-packages:
      - linux-firmware
      - wireless-regdb
    organize:
      lib/firmware: firmware
    prime:
      - firmware

build-packages:
    - android-tools-mkbootimg
    - bison
    - cpio
    - dpkg-dev
    - flex
    - gcc-aarch64-linux-gnu
    - libfdt-dev
    - libssl-dev
