# SPDX-License-Identifier: GPL-2.0
# Copyright (C) 2021 Canonical Ltd
name: imx-kernel
version: null
version-script: |
    . debian/debian.env
    dpkg-parsechangelog -l $DEBIAN/changelog -S version
summary: i.mx linux kernel
description: The i.MX Ubuntu kernel package as a snap
grade: stable
confinement: strict
type: kernel

parts:
  kernel:
    plugin: kernel
    source: .
    source-type: git
    kconfigflavour: generic
    kconfigs:
      - CONFIG_DEBUG_INFO=n
    override-build: |
      cp debian/scripts/retpoline-extract-one \
        $SNAPCRAFT_PART_BUILD/scripts/ubuntu-retpoline-extract-one
      snapcraftctl build
    kernel-with-firmware: false
  firmware:
    plugin: nil
    stage-packages:
      - linux-firmware
    organize:
      lib/firmware: firmware
    prime:
      - -usr
      - -lib

build-packages:
  - bison
  - device-tree-compiler
  - dpkg-dev
  - flex
  - libfdt-dev
  - libssl-dev
  - python3-cryptography
  - python3-pycryptodome
  - python3-pyelftools
  - python3-serial
  - u-boot-tools
  - wget
  - libjson-c-dev:${CRAFT_TARGET_ARCH}
  - libcryptsetup-dev:${CRAFT_TARGET_ARCH}
  - to armhf:
    - binutils-arm-linux-gnueabi
    - gcc-arm-linux-gnueabi
  - to arm64:
    - gcc-aarch64-linux-gnu
