name: ambarella-kernel
summary: Ambarella linux kernel for snappy
description: This is a Ambarella snapped kernel
grade: stable
confinement: strict
type: kernel
adopt-info: kernel

architectures:
  - build-on: [amd64, arm64]
    run-on: arm64

build-base: core18

parts:
    kernel:
        plugin: kernel
        source: .
        source-type: git
        kdefconfig: [ "defconfig", "ambarella_cv2_defconfig" ]
        kernel-with-firmware: false
        kernel-image-target: Image
        kconfigs:
            - CONFIG_DEBUG_INFO=n
        override-build: |
            cp debian/scripts/retpoline-extract-one \
                ${SNAPCRAFT_PART_BUILD}/scripts/ubuntu-retpoline-extract-one
            snapcraftctl build
            mkdir -p ${SNAPCRAFT_PART_INSTALL}/lib
            ln -sf ../modules ${SNAPCRAFT_PART_INSTALL}/lib/modules
            # snapcraftctl set-version $(git describe --tags | cut -c 19-)
            snapcraftctl set-version $(make kernelversion)
        stage:
            - System.map-*
            - config-*
            - initrd.img
            - kernel.img
            - lib
            - modules
            - -modules/*/build
            - -modules/*/source
        prime:
            - -initrd.img
            - -kernel.img
