# SPDX-License-Identifier: GPL-2.0
# Copyright (C) 2021 Canonical Ltd
name: imx-kernel
summary: i.mx linux kernel
description: The i.MX Ubuntu kernel package as a snap

grade: stable
build-base: core20
confinement: strict
type: kernel
adopt-info: kernel

architectures:
  - build-on: amd64
    run-on: armhf, arm64
  - build-on: armhf
    run-on: armhf
  - build-on: arm64
    run-on: arm64

# environment to run fde-setup hook
environment:
  LD_LIBRARY_PATH: ${SNAP}/usr/lib/${SNAPCRAFT_ARCH_TRIPLET}

parts:
  kernel:
    after:
      - firmware
      - optee-uc-fde-client
      - initrd-tools
      - snap-bootstrap
    plugin: kernel
    kernel-kdefconfig: [ "snappy_defconfig" ]
    kernel-with-firmware: false
    kernel-image-target:
      arm64: Image
      armhf: zImage
    kernel-initrd-compression: zstd
    kernel-initrd-stage-firmware: true
    kernel-initrd-addons:
      - usr/bin/fde-reveal-key
      - usr/bin/fde-setup
      - usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/libteec.so*
      - usr/lib/snapd/snap-bootstrap
    kernel-initrd-overlay: initrd-tools
    kernel-initrd-firmware:
      - firmware/imx/sdma/sdma-imx7d.bin
      - firmware/regulatory.db
      - firmware/regulatory.db.p7s
    build-environment:
      - PATH: "/usr/lib/ccache:${PATH}"
    override-build: |
      snapcraftctl build
      snapcraftctl set-version $(git --git-dir=${SNAPCRAFT_PROJECT_DIR}/.git describe --tags | cut -c 12-42)
    organize:
      kernel.img: Image
    override-prime: |
      snapcraftctl prime
      # Trim firmware
      trim_tool="https://git.launchpad.net/~canonical-kernel-snaps/+git/kernel-snaps-uc20/plain/trim-firmware"
      curl -s ${trim_tool} | bash /dev/stdin ${SNAPCRAFT_PRIME}
      # make sure we have all ath10 firmware files
      cp ${SNAPCRAFT_STAGE}/firmware/ath10k/QCA9377/hw1.0/* ${SNAPCRAFT_PRIME}/firmware/ath10k/QCA9377/hw1.0
    prime:
      - -initrd.img*
      - -Image*
      - -dtbs

  firmware:
    plugin: dump
    source: https://git.launchpad.net/~canonical-kernel-snaps/+git/kernel-snaps-uc22
    source-type: git
    source-branch: main
    stage-packages:
      - linux-firmware
      - wireless-regdb
    organize:
      lib/firmware: firmware
    stage:
      - -firmware/brcm/brcmfmac43455-sdio.bin
      - -firmware/brcm/brcmfmac43455-sdio.clm_blob
      - -firmware/brcm/brcmfmac4356-pcie.bin
      - -firmware/brcm/brcmfmac4356-pcie.clm_blob
    prime:
      - firmware

  firmware-nxp:
    after:
      - kernel
    plugin: dump
    source: https://github.com/NXP/imx-firmware.git
    source-type: git
    source-tag: lf-5.15.71_2.2.0
    organize:
      'cyw-wifi-bt/1CX_CYW4356/*': firmware/brcm/
      'cyw-wifi-bt/1FD_CYW4359/*': firmware/brcm/
      'cyw-wifi-bt/1MW_CYW43455/*': firmware/brcm/
      'brcm/': firmware/brcm/
      'nxp/FwImage_8997/*': firmware/nxp/
      'nxp/FwImage_8987/*': firmware/nxp/
      'nxp/wifi_mod_para.conf': firmware/nxp/
    stage:
      - firmware/brcm
      - firmware/nxp

  # optee signing keys: used for signing ot Trusted Applications
  optee-keys:
    plugin: dump
    source: https://git.launchpad.net/~ondrak/+git/dev-keys
    source-type: git
    source-branch: ta-keys
    organize:
      '*': ta-keys/
    prime:
       - -*

  optee-os:
    after:
      - optee-uc-fde
      - optee-keys
    plugin: nil
    source: https://github.com/nxp-imx/imx-optee-os.git
    source-type: git
    source-tag: lf-5.15.71_2.2.0
    source-depth: 1
    build-environment:
      # depending on architecture
      # on arm64: we are building optee-os only to get build export dependency to build REE app
      # on armhf: we are building optee-os to be included in FIT image
      - to armhf:
        - CROSS_COMPILE_ta_arm32: "${SNAPCRAFT_ARCH_TRIPLET}-"
        - PLATFORM: "vexpress-qemu_virt"
        - CFG_USER_TA_TARGETS: "ta_arm32"
        - CFG_NS_ENTRY_ADDR: "0x82100000"
        - CFG_PAGEABLE_ADDR: "0x86800000"
        - CFG_DT_ADDR: "0x83000000"
        # 1GB DDR
        # export CFG_DDR_SIZE=0x40000000
        # 512MB DDR
        - CFG_DDR_SIZE: "0x20000000"
        - CFG_TEE_RAM_VA_SIZE: "0x00400000"
        - PLATFORM: "imx"
        - PLATFORM_FLAVOR: "mx6sxsabreauto"
        - CFG_WERROR: "y"
      - to arm64:
        - CROSS_COMPILE_ta_arm64: "${SNAPCRAFT_ARCH_TRIPLET}-"
        - CFG_ARM64_core: "y"
        - PLATFORM: "vexpress-qemu_armv8a"
        - CFG_USER_TA_TARGETS: "ta_arm64"
      - ARCH: "arm"
      - CROSS_COMPILE: "${SNAPCRAFT_ARCH_TRIPLET}-"
      - CROSS_COMPILE_core: "${SNAPCRAFT_ARCH_TRIPLET}-"
      - DEBUG: "0"
      - CFG_TEE_CORE_DEBUG: "n"
      - CFG_TEE_BENCHMARK: "n"
      - TA_PUBLIC_KEY: "${SNAPCRAFT_STAGE}/ta-keys/ta_public.pem"
    override-build: |
      # add optee-uc-fde TA
      cp -r ${SNAPCRAFT_STAGE}/optee-uc-fde/ta/fde_key_handler ${SNAPCRAFT_PART_BUILD}/ta/
      export OPTEE_VERSION=$(head -1 CHANGELOG.md  | sed 's/# OP-TEE - version \(.*\) (.*/\1/g')-imx
      make O=${SNAPCRAFT_PART_BUILD}/out -j$(nproc)
      if [ "${SNAPCRAFT_TARGET_ARCH}" = "armhf" ]; then
        # now build optee-os once more with added early TAs
        make O=${SNAPCRAFT_PART_BUILD}/out -j$(nproc) \
          CFG_EARLY_TA=y \
          EARLY_TA_PATHS="out/ta/pkcs11/fd02c9da-306c-48c7-a49c-bbd827ae86ee.stripped.elf \
                  out/ta/fde_key_handler/fd1b2a86-3668-11eb-adc1-0242ac120002.stripped.elf"

        cp ${SNAPCRAFT_PART_BUILD}/out/core/tee-raw.bin \
          ${SNAPCRAFT_PART_INSTALL}/tee.mx6sx.bin
      fi
      cp -r ${SNAPCRAFT_PART_BUILD}/out/export-ta_arm* ${SNAPCRAFT_PART_INSTALL}/export-ta_arm
    prime:
      - -*

  optee-client:
    plugin: nil
    source: https://github.com/OP-TEE/optee_client.git
    source-type: git
    source-tag: 3.19.0
    build-environment:
      - to armhf:
        - ARCH: "arm"
      - else:
        - ARCH: "${SNAPCRAFT_TARGET_ARCH}"
      - CROSS_COMPILE: "${SNAPCRAFT_ARCH_TRIPLET}-"
      - DEBUG: "0"
      - CFG_TEE_CLIENT_LOAD_PATH: ""
      - CFG_TA_TEST_PATH: "0"
      - SBINDIR: "/usr/sbin"
      - LIBDIR: "/usr/lib/${SNAPCRAFT_ARCH_TRIPLET}"
      - DESTDIR: "${SNAPCRAFT_PART_INSTALL}"
    override-build: |
      make O=${SNAPCRAFT_PART_BUILD}/out -j$(nproc)
      make install O=${SNAPCRAFT_PART_BUILD}/out
    prime:
      - usr/lib/*/lib*so*

  optee-uc-fde:
    plugin: dump
    source: https://git.launchpad.net/~ondrak/+git/optee-uc-fde
    source-type: git
    organize:
      '*': optee-uc-fde/
    prime:
      - -*

  optee-uc-fde-client:
    after:
      - optee-client
      - optee-os
      - optee-uc-fde
    plugin: nil
    source-type: local
    build-environment:
      - to armhf:
        - ARCH: "arm"
      - else:
        - ARCH: "${SNAPCRAFT_TARGET_ARCH}"
      - CROSS_COMPILE: "${SNAPCRAFT_ARCH_TRIPLET}-"
      # we are not using TA build here (early TA is used), so
      # it does not matter what key is used to sign built TA
      # support cross build
      - TA_DEV_KIT_DIR: "${SNAPCRAFT_STAGE}/export-ta_arm"
      - OPTEE_CLIENT_EXPORT: "${SNAPCRAFT_STAGE}/usr"
      - DESTDIR: "${SNAPCRAFT_PART_INSTALL}"
    override-build: |
      make -C ${SNAPCRAFT_STAGE}/optee-uc-fde O=${SNAPCRAFT_PART_BUILD}/out fde-key-manager fde-reveal-key fde-setup
      make -C ${SNAPCRAFT_STAGE}/optee-uc-fde O=${SNAPCRAFT_PART_BUILD}/out fde-key-manager fde-reveal-key fde-setup install
      install -D -m 755 ${SNAPCRAFT_PART_INSTALL}/usr/bin/fde-setup ${SNAPCRAFT_PART_INSTALL}/meta/hooks/fde-setup
      ln -sf fde-reveal-key ${SNAPCRAFT_PART_INSTALL}/usr/bin/fde-setup
    prime:
      - meta/

  initrd-tools:
    plugin: nil
    stage-packages: # extra tools needed to PoC
      - cryptsetup
      - cryptsetup-bin
      - dosfstools
      - e2fsprogs
      - fdisk
      - libfdisk1
      - libpopt0
      - libreadline8
      - libsmartcols1
      - libtinfo6
      - tar
    override-build: |
      # we want only partx from util-linux
      # reset path so we don't pick tools from part install (not a best of ideas while cross building)
      export PATH="/usr/lib/ccache:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin"
      apt-get download util-linux libc6
      dpkg -x ${SNAPCRAFT_PART_BUILD}/util-linux*.deb ${SNAPCRAFT_PART_BUILD}/unpacked
      dpkg -x ${SNAPCRAFT_PART_BUILD}/libc6*.deb ${SNAPCRAFT_PART_BUILD}/unpacked
      cp ${SNAPCRAFT_PART_BUILD}/unpacked/usr/bin/partx ${SNAPCRAFT_PART_INSTALL}/usr/bin/partx
      cp ${SNAPCRAFT_PART_BUILD}/unpacked/lib/${SNAPCRAFT_ARCH_TRIPLET}/libresolv* ${SNAPCRAFT_PART_INSTALL}/usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/
      # manually organize otherwise craft fails to merge dirs
      mv ${SNAPCRAFT_PART_INSTALL}/bin/*       ${SNAPCRAFT_PART_INSTALL}/usr/bin
      mv ${SNAPCRAFT_PART_INSTALL}/sbin/*      ${SNAPCRAFT_PART_INSTALL}/usr/bin
      mv ${SNAPCRAFT_PART_INSTALL}/usr/sbin/*  ${SNAPCRAFT_PART_INSTALL}/usr/bin
      mv ${SNAPCRAFT_PART_INSTALL}/lib/${SNAPCRAFT_ARCH_TRIPLET}/* ${SNAPCRAFT_PART_INSTALL}/usr/lib/${SNAPCRAFT_ARCH_TRIPLET}
      cp ${SNAPCRAFT_PROJECT_DIR}/initrd-overlay/the-modeenv-focal ${SNAPCRAFT_PART_INSTALL}/usr/lib/the-modeenv
      mkdir -p ${SNAPCRAFT_PART_INSTALL}/usr/lib/systemd/system-generators
      cp ${SNAPCRAFT_PROJECT_DIR}/initrd-overlay/journald-console-focal ${SNAPCRAFT_PART_INSTALL}/usr/lib/systemd/system-generators/journald-console
    organize:
      etc:      initrd-tools/etc
      usr/bin:  initrd-tools/usr/bin
      usr/lib:  initrd-tools/usr/lib
    stage:
      - initrd-tools
    prime:
      - -*

  snap-bootstrap:
    plugin: nil
    override-build: |
      mkdir -p ${SNAPCRAFT_PART_INSTALL}/usr/lib/snapd
      cp /home/ubuntu/snapd-build/snap-bootstrap.${SNAPCRAFT_TARGET_ARCH} ${SNAPCRAFT_PART_INSTALL}/usr/lib/snapd/snap-bootstrap
    prime:
      - -*

  test-keys:
    plugin: dump
    source: https://git.launchpad.net/~ondrak/+git/dev-keys
    source-type: git
    source-branch: master
    organize:
      '*': signing-key/
    prime:
      - -*

  fit-image:
    after:
      - kernel
      - test-keys
      - optee-os
    plugin: nil
    override-build: |
      cp ${SNAPCRAFT_PROJECT_DIR}/kernel_*.its ${SNAPCRAFT_STAGE}
      # include key dir in case there are keys available
      mkimage \
        -f ${SNAPCRAFT_STAGE}/kernel_${SNAPCRAFT_TARGET_ARCH}.its \
        -r ${SNAPCRAFT_PART_INSTALL}/kernel.img \
        -k ${SNAPCRAFT_STAGE}/signing-key

build-packages:
  - bison
  - device-tree-compiler
  - dpkg-dev
  - flex
  - libfdt-dev
  - libssl-dev
  - python3-cryptography
  - python3-pycryptodome
  - python3-pyelftools
  - python3-serial
  - u-boot-tools
  - wget
  - libjson-c-dev:${SNAPCRAFT_TARGET_ARCH}
  - libcryptsetup-dev:${SNAPCRAFT_TARGET_ARCH}
  - to armhf:
    - binutils-arm-linux-gnueabi
    - gcc-arm-linux-gnueabi
  - to arm64:
    - on amd64:
      - gcc-aarch64-linux-gnu
    - on arm64:
      - gcc
