name: snapdragon-kernel
summary: Snapdragon kernel
description: This is a snapdragon snapped kernel, based off linaro kernel
grade: stable
confinement: strict
type: kernel
adopt-info: kernel

architectures:
  - build-on: [amd64, arm64]
    run-on: arm64

build-base: core20

parts:
  kernel:
    after:
      - firmware
    plugin: x-kernel
    source: .
    source-type: git
    kdefconfig: [ "snappy_defconfig" ]
    kernel-with-firmware: false
    kernel-image-target: Image.gz
    kconfigs:
      - CONFIG_DEBUG_INFO=n
    kernel-initrd-compression: lz4
    kernel-initrd-modules:
      - qcom-emac
      - phy-qcom-qusb2
      - slimbus
      - xhci-hcd
      - libarc4
    kernel-initrd-configured-modules:
      - atl1c
      - phy-qcom-qusb2
    override-pull: |
      snapcraftctl pull
      git clone --depth=1 https://github.com/openzfs/zfs ${SNAPCRAFT_PART_SRC}/zfs -b master
    override-build: |
      snapcraftctl build
      kernel_version="$(git --git-dir=${SNAPCRAFT_PART_SRC}/.git describe --tags  | cut -c 14-)"
      snapcraftctl set-version ${kernel_version}
      ln -sf ${SNAPCRAFT_PART_SRC}/zfs ${SNAPCRAFT_PART_BUILD}/zfs
      cd ${SNAPCRAFT_PART_BUILD}/zfs
      ./autogen.sh
      ./configure --with-linux=${SNAPCRAFT_PART_SRC} --with-linux-obj=${SNAPCRAFT_PART_BUILD} --with-config=kernel
      make -j$(nproc)
      make install DESTDIR=${SNAPCRAFT_PART_INSTALL}/zfs
      release_version="$(ls ${SNAPCRAFT_PART_INSTALL}/modules)"
      mv ${SNAPCRAFT_PART_INSTALL}/zfs/lib/modules/${release_version}/extra \
         ${SNAPCRAFT_PART_INSTALL}/modules/${release_version}
      # rebuild module dependencies
      depmod -b ${SNAPCRAFT_PART_INSTALL} ${release_version}
    stage:
      - dtbs
      - System.map-*
      - config-*
      - initrd.img
      - kernel.img
      - modules
    prime:
      - -dtbs
      - -initrd.img
      - -kernel.img

  bootimg:
    plugin: nil
    after:
      - kernel
    override-build: |
      cat ${SNAPCRAFT_STAGE}/kernel.img \
          ${SNAPCRAFT_STAGE}/dtbs/qcom/apq8096-db820c.dtb \
          > Image.gz+dtbs
      mkbootimg \
        --kernel Image.gz+dtbs \
        --ramdisk ${SNAPCRAFT_STAGE}/initrd.img \
        --output ${SNAPCRAFT_PART_INSTALL}/boot.img \
        --pagesize 4096 \
        --base 0x80000000 \
        --kernel_offset 0x8000 \
        --ramdisk_offset 0x1000000 \
        --tags_offset 0x100 \
        --cmdline 'console=tty0 console=ttyMSM0,115200n8 clk_ignore_unused pd_ignore_unused'
    prime:
      - boot.img

  firmware:
    plugin: nil
    stage-packages:
      - linux-firmware
      - wireless-regdb
    override-pull: |
      for f in firmware-atheros firmware-qcom-dragonboard410c firmware-qcom-dragonboard820c firmware-qcom-dragonboard845c firmware-qcom-media firmware-qcom-soc
      do
        version="$(curl -s http://obs.linaro.org/linaro-overlay-sid/sid/Packages.gz | zcat | grep "${f}" |grep "Filename" | tail -1 | awk '{ print $2}' | cut -c3-)"
        echo "current_version=${version}"
        curl -O http://obs.linaro.org/linaro-overlay-sid/sid/${version}
      done
    override-build: |
      find ${SNAPCRAFT_PART_SRC} -name "*.deb" -exec dpkg -x {} ${SNAPCRAFT_PART_INSTALL} \;
    stage:
      - -firmware/amd
      - -firmware/amdgpu
      - -firmware/asihpi
      - -firmware/cavium
      - -firmware/cxgb3
      - -firmware/cxgb4
      - -firmware/dpaa2
      - -firmware/i915
      - -firmware/intel
      - -firmware/iwlwifi-*
      - -firmware/liquidio
      - -firmware/matrox
      - -firmware/mediatek
      - -firmware/mellanox
      - -firmware/mrvl
      - -firmware/moxa
      - -firmware/netronome
      - -firmware/nvidia
      - -firmware/qed
      - -firmware/radeon
      - -firmware/rockchip
      - -firmware/ath3k-1.fw
      - -firmware/s5p*
      - -usr
      - -lib
    organize:
      lib/firmware: firmware
    prime:
      - -usr
      - -lib

build-packages:
    - dpkg-dev
    - android-tools-mkbootimg
    - libssl-dev
    - libfdt-dev
    - cpio
    - flex
    - bison
    - wget
    - gcc-aarch64-linux-gnu
    - libjson-c-dev:arm64
    - autoconf
    - automake
    - libblkid-dev
    - libtool
    - python3
